### ISSUE TITLE
Typescript compilation error

### ISSUE THREAD

**Issue by victorbartel** [dex4er/js-promise-writable#1]
Hi,
I get following TS compilation error:
```
ERROR in .../node_modules/promise-socket/lib/promise-socket.d.ts
(3,8): error TS1192: Module '"net"' has no default export.

ERROR in .../node_modules/promise-socket/lib/promise-socket.d.ts
(7,78): error TS2344: Type 'TSocket' does not satisfy the constraint 'Duplex'.
```

**Comment by victorbartel** [comment]
In order to be able to compile your type definition should look like below:
```typescript
/// <reference types="node" />

import * as net from "net";

import PromiseDuplex from 'promise-duplex'

export class PromiseSocket<TSocket extends net.Socket> extends PromiseDuplex<TSocket> {
  constructor (socket?: TSocket)

  connect(port: number): Promise<void>
  connect(path: string): Promise<void>
  connect(options: object): Promise<void>

  setTimeout (timeout: number): void
}

export default PromiseSocket

```

**Comment by dex4er** [comment]
What version of promise-socket and what version of typescript?

The latest Typescript 2.7 obsoleted `import *` notation and now it is compatible with ES6 notation which will be soon implemented for Node.js.

I do not plan to provide support for older syntax without `--esModuleInterop` options as far as it is now required by https://github.com/DefinitelyTyped/DefinitelyTyped project for the newest typings.

**Comment by victorbartel** [comment]
Hi,

Indeed I was using TypeScript 2.6.2, which is not such an old thing. Will try to update.
