### ISSUE TITLE
writeAll ends stream

### ISSUE THREAD

**Issue by markb1** [dex4er/js-promise-writable#2]
Starting on line 131 of promise-writable.ts in writeAll():

          if (part * chunkSize >= content.length) {
            stream.end()
          }

That appears to kill the stream as soon as all the data is written, and that's also what I see in my testing, too. I'm perplexed by why this is there. I want to read some data, write some data, and repeat. It seems like I should use writeAll to make sure all my data is written before moving on. But once I've done that, the stream is ended!

**Comment by markb1** [comment]
After some further review, I think write() may actually be the correct thing in my case, because it will not fulfill its promise before all the data is sent.

But then, I'm not sure what the purpose of writeAll is. And call to end still seems like a bug.

**Comment by dex4er** [comment]
@markb1 I think it might be a mistake in this API. `writeAll` works with larger buffers and then splits automatically by chunks. I think it should not close stream, as far as I explicitly close it in an example script: https://github.com/dex4er/js-promise-writable/blob/299d20c9f8bc11f9ebfbaf754f1e4e8afed4cc82/examples/write-all-ts.ts#L15

**Comment by markb1** [comment]
Thank you!
